### ISSUE TITLE
Split BMO e2e tests into separate spec and test files

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/baremetal-operator#1626]
This is a bit more advanced. If you are new to go and/or ginkgo it may not be the best to start with.

The e2e tests are currently written as plain tests, each test in its own file. To make the structure clearer and the code reusable, we should split them up so that we have separate (non-test) files with procedure implementations. Each test can then call an implementation with a specific configuration.
For example, we could have one implementation of an upgrade test. This could then be called twice to test upgrades from both v0.4 and v0.5 to main.

**What you need to do**

1. Pick a test from [here](https://github.com/metal3-io/baremetal-operator/tree/main/test/e2e)
2. Identify the relevant input and what the test does
3. Implement the test separately and create an input struct with all relevant input
4. Change the original test to call the new implementation

**Tasks**

- [ ] [Basic ops](https://github.com/metal3-io/baremetal-operator/blob/main/test/e2e/basic_ops_test.go)
- [ ] [External inspection](https://github.com/metal3-io/baremetal-operator/blob/main/test/e2e/external_inspection_test.go)
- [ ] [Inspection](https://github.com/metal3-io/baremetal-operator/blob/main/test/e2e/inspection_test.go)
- [ ] [Provision](https://github.com/metal3-io/baremetal-operator/blob/main/test/e2e/provisioning_and_annotation_test.go) (I think the [live-iso test](https://github.com/metal3-io/baremetal-operator/blob/main/test/e2e/live_iso_test.go) could be another call to this with different config.)
- [ ] [Re-inspection](https://github.com/metal3-io/baremetal-operator/blob/main/test/e2e/re_inspection_test.go)
- [ ] [Upgrade](https://github.com/metal3-io/baremetal-operator/blob/main/test/e2e/upgrade_test.go)

**Comment by jackjii79** [comment]
Hi @lentzi90 
I made some refactor against the `upgrade_test`, but i m not sure if my changes would align with the expectation consider this is my first PR in this repo, could you please take a preview about https://github.com/metal3-io/baremetal-operator/pull/1637 ?
